[general]
import = [
  "~/.config/alacritty/themes/rose-pine-moon.toml"
]

[font]
size = 20

[font.normal]
# family = "ComicCodeLigatures Nerd Font"
family = "Codelia Nerd Font"

[font.offset]
x = 0
y = 10

[window]
dynamic_padding = true
dynamic_title = false

[window.dimensions]
columns = 88
lines = 28
