[font]
size = 20

[font.normal]
family = "ComicCodeLigatures Nerd Font"

[font.offset]
x = -1
y = 0

[general]
import = [
  # "~/.config/alacritty/themes/moonlight_ii_vscode.toml"
  # "~/.config/alacritty/themes/inferno.toml"
  # "~/.config/alacritty/themes/aura.toml"
  # "~/.config/alacritty/themes/ubuntu.toml"
  # "~/.config/alacritty/themes/marine_dark.toml"
  # "~/.config/alacritty/themes/baitong.toml"
  "~/.config/alacritty/themes/night_owl.toml"
]

[window]
dynamic_padding = true
dynamic_title = false

[window.dimensions]
columns = 88
lines = 28
