# Default colors

# Bright colors
[colors.bright]
black = "#575656"
red = "#EF5350"
green = "#22da6e"
yellow = "#ffeb95"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#7fdbca"
white = "#ffffff"

# Cursor colors
[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.footer_bar]
foreground = "#ffffff"
background = "#1d3b53"

# Normal colors
[colors.normal]
black = "#011627"
red = "#EF5350"
green = "#22da6e"
yellow = "#c5e478"
blue = "#82AAFF"
magenta = "#C792EA"
cyan = "#21c7a8"
white = "#ffffff"

[colors.primary]
background = "#011627"
foreground = "#d6deeb"
[colors.search]

[colors.search.focused_match]
foreground = "#ffffff"
background = "#22da6e"

# Search colors
[colors.search.matches]
foreground = "#000000"
background = "#22da6e"

# Selection colors
[colors.selection]
text = "#ffffff"
background = "#0d486e"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "#22da6e"
