{
  imports = [
    ./admin-user.nix
    ./base-system.nix
    ./caddy.nix
    ./frpc.nix
    ./frps.nix
    ./mediawiki.nix
    ./minecraft.nix
    ./nvidia.nix
    ./ollama.nix
    ./openssh.nix
    ./satisfactory.nix
    ./satisfactory-fjij.nix
    ./sops.nix
    ./tailscale.nix
    ./willh-user.nix
  ];
}
